# Generated by Django 3.1.7 on 2021-03-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnotationServer', '0002_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='class_label',
            field=models.IntegerField(default=0),
        ),
    ]
