# Generated by Django 3.1.7 on 2021-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnotationServer', '0003_record_class_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='img_id',
            field=models.IntegerField(default=-1),
        ),
    ]
